import os
print(os.environ)
print("-----")
print(os.path)
print("-----")
print(dir(os))
print("-----")
print(os.getpid())
print("-----")
print(os.getcwd())
print("-----")
print(type(os.getcwd()))
print("-----")
print(os.pathsep,os.sep,os.pardir,os.curdir,os.linesep)
print("-----")
os.path.split(os.getcwd())
print("-----")
print(os.system('ls'))
print("-----")
print(os.system('cat helloT.py'))
print("-----")
print(type(os.system('cat helloT.py')))
print('-----')
print(os.system('python helloT.py'))
